apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apeiron-tls
spec:
  commonName: apeiron
  dnsNames:
    - apeiron
  issuerRef:
    kind: ClusterIssuer
    name: nishir
  secretName: apeiron-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
