apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
spec:
  template:
    spec:
      containers:
        - name: apeiron
          env:
            - name: LOG_LEVEL
              value: debug
