apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
spec:
  template:
    spec:
      containers:
        - name: apeiron
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MLFLOW_EXPERIMENT_NAME
              value: Apeiron
