apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: mlflow
    newName: ghcr.io/mlflow/mlflow
    newTag: v3.4.0
resources:
  - ingress.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
labels:
  - pairs:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/part-of: baguetto
      app.kubernetes.io/version: "3.4.0"
