apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-runs-data
  namespace: shikanime-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: nishir-fast
  volumeMode: Filesystem
  volumeName: mlflow-runs-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-data
  namespace: shikanime-studio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: nishir-fast
  volumeMode: Filesystem
  volumeName: mlflow-artifacts-data
