apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlflow
  namespace: shikanime-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow
          command:
            - mlflow
          args:
            - server
            - --host=0.0.0.0
            - --port=5000
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: mlflow-runs
              mountPath: /app/mlruns
            - name: mlflow-artifacts
              mountPath: /app/mlartifacts
      securityContext:
        fsGroup: 1001
      volumes:
        - name: mlflow-runs
          persistentVolumeClaim:
            claimName: mlflow-runs-data
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-data
