apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: apeiron
    newName: ghcr.io/shikanime-studio/apeiron
resources:
  - sts.yaml
  - svc.yaml
  - vpa.yaml
labels:
  - pairs:
      app.kubernetes.io/component: agent
      app.kubernetes.io/name: apeiron
      app.kubernetes.io/part-of: baguetto
