apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
  namespace: shikanime-studio
spec:
  serviceName: apeiron
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apeiron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apeiron
    spec:
      containers:
        - name: apeiron
          image: apeiron
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apeiron
                  key: discord_token
            - name: LOG_FORMAT
              value: uvicorn
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apeiron
                  key: mistral_api_key
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 60
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            failureThreshold: 30
