apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
spec:
  serviceName: apeiron
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apeiron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apeiron
    spec:
      containers:
        - name: apeiron
          image: apeiron
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 60
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            failureThreshold: 30
