apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: apeiron
  namespace: shikanime-studio
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: apeiron
  updatePolicy:
    updateMode: Auto
