apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apeiron
  namespace: shikanime-studio
spec:
  template:
    spec:
      containers:
        - name: apeiron
          env:
            - name: APEIRON_AGENT
              value: teto
          envFrom:
            - secretRef:
                name: apeiron
